---
title: "Batch Formatting Geonetworkd"
author: "M. Houle"
date: "January 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This script intend to create metadata into Geonetwork standard for dataset of the same format, such as species distribution for 89 birds species. 

First, metadata should be created for one species inside Geonetwork and exported as a zip file in a work folder. Metadata xml is then process by the script to create new metadata with only bird name replaced.  

```{r pressure, echo=FALSE} 

```

```{r Batch upload Species Distribution dataset }  
library(XML)
library(utils)

#List birds table 
birdtbl <- ("../data/birdAcronyme.csv")
bird <- read.csv(birdtbl, sep="\t", header=TRUE)
lsbird <- as.vector(bird[,1])

gnDir <- "../GNmetadata/templateSpeciesDistribution/data/metadata"
gnVersion <-readLines(file(paste0(gnDir,"/metadata.xml")), warn=FALSE)

xml_update <- sapply(lsbird,function(x) {
                    dirTo <- file.path("../../toGN")
                    xml_updated <-gsub("XXXX",x,gnVersion)
                    writeLines(xml_updated, file(paste0(dirTo,"/",x,".xml")))
})

```
